#!/usr/bin/env python3

# Copyright (c) 2021, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: LGPL-2.1-only

from argparse import ArgumentParser

def show_sfp_monitoring_status():

def show_sfp_monitoring_events():

arg_parser = ArgumentParser()
arg_parser.add_argument("--cmd", help="Get monitoring status/events",
                        choices=['status', 'events'], dest="cmd",
                        required=True)
args = arg_parser.parse_args()

if args.cmd == "status":
    show_sfp_monitoring_status()
elif args.cmd == "events":
    show_sfp_monitoring_events()
